name: Node.js Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package-nr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          
      - name: Version Check
        uses: EndBug/version-check@v2.1.0
        id: check
        
      - name: Set up node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@endbug"

      - name: Set up gpr
        if: steps.check.outputs.changed == 'true'
        run: npm run gpr-setup
        
      - name: Publish package to GPR
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


