name: Node.js Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package-nr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          
      - name: Extract version
        id: package
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Print version
        run: echo ${{ steps.package.outputs.version }}
        
        
  publish-package:
    needs: package-nr
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
           
# Tried this solution too, but for couldn't quite understand why it didnt work        
#       - name: GPR
#         if: steps.check.outputs.changed == 'true'
#         uses: actions/setup-node@v1
#         with:
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
               
