name: Node.js Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci
      - name: Extract version
        id: package
        uses: Saionaro/extract-package-version@v1.1.1
      - name: Print version
        run: echo ${{ steps.package.outputs.version }}
